#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if command -v php &> /dev/null; then
	echo ""
	echo "Using PHP version..."
	echo ""
	$DIR/../ihtml-php/ihtml "$@"
elif command -v node &> /dev/null; then
	echo ""
	echo "Using NodeJS version..."
	echo ""
	$DIR/../ihtml-node/ihtml "$@"
else
	echo "no interpreter found. please install node, php or any other supported interpreter"
	exit 1
fi

